module.exports = [
  "327953@mariscollege.nl",
  "an4g7k@gmail.com",
  "andrew@win11react.com",
  "contact@mail.badboy.is-a.dev",
  "kumarjhaabhishek2002@gmail.com",
  "lukasbatema@gmail.com",
  "lukasbatema@mg.batemadevelopment.com",
  "mahir@molai.dev",
  "mousemoosz@protonmail.com",
  "omsenjalia@gmail.com",
  "therealhackermon@gmail.com",
  "william@williamharrison.dev",
  "w11bot@andrewstech.me",
  "yashash1511@gmail.com",
];
